### ISSUE TITLE
HttpComponentsRequestBuilder - erase of the QueryParams 

### ISSUE THREAD

**Issue by To-da** [lukas-krecan/rest-fire#1]
If you are using [HttpComponentsRequestBuilder](https://github.com/lukas-krecan/rest-fire/blob/master/src/main/java/net/javacrumbs/restfire/httpcomponents/HttpComponentsRequestBuilder.java) (for example by creating request using [RequestFactory](https://github.com/lukas-krecan/rest-fire/blob/master/src/main/java/net/javacrumbs/restfire/RequestFactory.java)) and trying to [setup query params](https://github.com/lukas-krecan/rest-fire/blob/master/src/main/java/net/javacrumbs/restfire/httpcomponents/HttpComponentsRequestBuilder.java#L105) and after that set ['destination' address by 'to' method](https://github.com/lukas-krecan/rest-fire/blob/master/src/main/java/net/javacrumbs/restfire/httpcomponents/HttpComponentsRequestBuilder.java#L78) it will result in request that doesn't contain any parameter. If you try to build request in opposite order than the result is ok. 
The glitch is [here](https://github.com/lukas-krecan/rest-fire/blob/master/src/main/java/net/javacrumbs/restfire/httpcomponents/HttpComponentsRequestBuilder.java#L83) - during HttpComponentsRequestBuilder.to(URI address) method is the internal URIBuilder instance replaced by the new one without query params.

**Comment by lukas-krecan** [comment]
Fixed in 0.3.2

**Comment by To-da** [comment]
Fix confirmed
